version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: charges
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  spring-app:
    image: charging-solutions-platform:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/charges
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123321
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    expose:
      - 9090

volumes:
  postgres-data:
